name: Docker CI

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: car1pro

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      - name: Tag Image
        run: docker tag $IMAGE_NAME ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest